import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// We'll rely on a custom generator (configured in docusaurus.config.ts)
	// to filter out any docs that set `hide_from_sidebar: true` in front matter.
	defaultSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
